<template>
    <div>
      <Hero/>
      <IndexExperienceImpact/>
      <IndexAboutUs/>
      <IndexServices/>
      <Process/>
      <CourseCoursesSection/>
      <Cases/>
      <TeamSection/>
      <CareerCareersSection/>
      <IndexTestimonials/>
      <IndexFaqSection/>
      <ContactSection/>
    </div>
</template>